---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - builder-hub.dev
  resources:
  - buildkitbuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - builder-hub.dev
  resources:
  - buildkitbuilders/finalizers
  verbs:
  - update
- apiGroups:
  - builder-hub.dev
  resources:
  - buildkitbuilders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - builder-template.builder-hub.dev
  resources:
  - buildkitbuildertemplates
  verbs:
  - get
  - list
  - watch
