name: On Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: builderhub/actions-internal/.github/workflows/build-push-image.yaml@main
    with:
      build-type: dockerfile
      image-name: build-operator
      dockerfile: Dockerfile
      context: .
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
