name: On Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: builderhub/actions-internal/.github/workflows/build-push-image.yaml@main
    with:
      image-name: build-operator
      dockerfile: Dockerfile
      context: .
      push-to-registry: ${{ github.event_name == 'push' }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
